// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;

namespace TestNs
{
    public static partial class OrderForges
    {
        /// <summary>Maps <see cref="Order"/> to <see cref="OrderDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial OrderDto ToDto(Order source)
        #line default
        {
            var __result = new OrderDto();
            __result.Status = source.Status.ToString();
            return __result;
        }

    }

    /// <summary>Extension method forwarders for <see cref="OrderForges"/>. Auto-generated by FreakyKit.Forge.</summary>
    public static class OrderForgesExtensions
    {

        /// <summary>Extension method forwarder to <see cref="OrderForges.ToDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static OrderDto ToDto(this Order source)
        {
            return OrderForges.ToDto(source);
        }
    }
}
