// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;

namespace TestNs
{
    public static partial class PersonForges
    {
        /// <summary>Maps <see cref="Address"/> to <see cref="AddressDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial AddressDto ToAddressDto(Address source)
        #line default
        {
            var __result = new AddressDto();
            __result.City = source.City;
            return __result;
        }

        /// <summary>Maps <see cref="Person"/> to <see cref="PersonDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial PersonDto ToDto(Person source)
        #line default
        {
            var __result = new PersonDto();
            __result.Name = source.Name;
            __result.Home = source.Home != null ? ToAddressDto(source.Home) : null;
            return __result;
        }

    }

    /// <summary>Extension method forwarders for <see cref="PersonForges"/>. Auto-generated by FreakyKit.Forge.</summary>
    public static class PersonForgesExtensions
    {

        /// <summary>Extension method forwarder to <see cref="PersonForges.ToAddressDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static AddressDto ToAddressDto(this Address source)
        {
            return PersonForges.ToAddressDto(source);
        }

        /// <summary>Extension method forwarder to <see cref="PersonForges.ToDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static PersonDto ToDto(this Person source)
        {
            return PersonForges.ToDto(source);
        }
    }
}
