// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;

namespace TestNs
{
    public static partial class AnimalForges
    {
        /// <summary>Maps <see cref="Dog"/> to <see cref="DogDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial DogDto MapDog(Dog source)
        #line default
        {
            var __result = new DogDto();
            __result.Breed = source.Breed;
            __result.Name = source.Name;
            return __result;
        }

        /// <summary>Maps <see cref="Cat"/> to <see cref="CatDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial CatDto MapCat(Cat source)
        #line default
        {
            var __result = new CatDto();
            __result.Indoor = source.Indoor;
            __result.Name = source.Name;
            return __result;
        }

        /// <summary>Dispatches <paramref name="source"/> to the appropriate forge method based on runtime type. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial AnimalDto MapAny(Animal source)
        #line default
        {
            if (source is null) throw new ArgumentNullException(nameof(source));
            return source switch
            {
                TestNs.Dog __p0 => MapDog(__p0),
                TestNs.Cat __p1 => MapCat(__p1),
                _ => throw new InvalidOperationException("No polymorphic mapping for " + source.GetType()),
            };
        }

    }

    /// <summary>Extension method forwarders for <see cref="AnimalForges"/>. Auto-generated by FreakyKit.Forge.</summary>
    public static class AnimalForgesExtensions
    {

        /// <summary>Extension method forwarder to <see cref="AnimalForges.MapDog"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static DogDto MapDog(this Dog source)
        {
            return AnimalForges.MapDog(source);
        }

        /// <summary>Extension method forwarder to <see cref="AnimalForges.MapCat"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static CatDto MapCat(this Cat source)
        {
            return AnimalForges.MapCat(source);
        }

        /// <summary>Extension method forwarder to <see cref="AnimalForges.MapAny"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static AnimalDto MapAny(this Animal source)
        {
            return AnimalForges.MapAny(source);
        }
    }
}
