// <auto-generated/>
#nullable enable
#pragma warning disable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;

namespace TestNs
{
    public static partial class PersonForges
    {
        /// <summary>Updates <paramref name="dest"/> from <paramref name="source"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static partial void UpdateDto(Person source, PersonDto dest)
        #line default
        {
            dest.Name = source.Name;
        }

    }

    /// <summary>Extension method forwarders for <see cref="PersonForges"/>. Auto-generated by FreakyKit.Forge.</summary>
    public static class PersonForgesExtensions
    {

        /// <summary>Extension method forwarder to <see cref="PersonForges.UpdateDto"/>. Auto-generated by FreakyKit.Forge.</summary>
        [GeneratedCode("FreakyKit.Forge.Generator", "1.0.0")]
        [DebuggerStepThrough]
        public static void UpdateDto(this Person source, PersonDto dest)
        {
            PersonForges.UpdateDto(source, dest);
        }
    }
}
